package com.demo.motherbuilder;

import com.demo.motherbuilder.entity.Address;
import com.demo.motherbuilder.entity.Currency;
import com.demo.motherbuilder.entity.Customer;
import com.demo.motherbuilder.entity.CustomerType;
import com.demo.motherbuilder.entity.ItemType;
import com.demo.motherbuilder.entity.Order;
import com.demo.motherbuilder.entity.OrderItem;
import com.demo.motherbuilder.entity.OrderStatus;
import com.demo.motherbuilder.entity.PaymentProcessor;
import com.demo.motherbuilder.entity.PaymentReference;
import com.demo.motherbuilder.entity.PaymentStatus;
import com.demo.motherbuilder.entity.Price;
import com.demo.motherbuilder.repository.OrderRepository;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase;
import org.springframework.context.annotation.Import;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.NoSuchElementException;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;

/**
 * Strategy: Native Lombok Builders
 * * This class illustrates the high maintenance cost of manual construction.
 * Every test is coupled to the technical structure of the entity graph.
 */
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@Import(TestcontainersConfiguration.class)
@DisplayName("Native Builder Strategy")
class BuilderOrderRepositoryTest {

    // ================================================================ Constants
    // Same semantic constants as SqlOrderRepositoryTest — no fixed UUIDs
    // here: IDs are generated by JPA at save time.

    private static final int EXPECTED_TOP_LEVEL_ITEMS_SCENARIO_1 = 2;
    private static final int EXPECTED_CHILDREN_IN_PACKAGE = 1;
    private static final int EXPECTED_TOP_LEVEL_ITEMS_SCENARIO_2 = 3;

    @Autowired
    private OrderRepository orderRepository;

    @PersistenceContext
    private EntityManager entityManager;

    @Test
    @DisplayName("Builder ⚠️ [Readability] Complex hierarchy — the entire graph is instantiated manually")
    void should_save_and_retrieve_complex_order_hierarchy() {

        // ── Currency — must be built before any Price ───────────────────────
        Currency euros = Currency.builder()
                .code("EUR")
                .symbol("€")
                .name("Euro")
                .build();

        // ── Embedded Address — must be built before Customer ────────────────
        Address address = Address.builder()
                .street("1 rue de la Paix")
                .postalCode("59000")
                .city("Lille")
                .state("Hauts-de-France")
                .country("France")
                .build();

        // ── Customer (INDIVIDUAL) ───────────────────────────────────────────
        Customer customer = Customer.builder()
                .customerType(CustomerType.INDIVIDUAL)
                .firstName("Jean")
                .lastName("Dupont")
                .birthDate(LocalDate.of(1985, 6, 15))
                .email("jean.dupont@example.com")
                .phoneNumber("+33612345678")
                .address(address)
                .build();

        // ── PaymentReference (SUCCESS) ─────────────────────────────────────
        PaymentReference payment = PaymentReference.builder()
                .transactionId("TXN-BUILDER-001")
                .status(PaymentStatus.SUCCESS)
                .paymentProcessor(PaymentProcessor.STRIPE)
                .build();

        // ── Sub-item: PRODUCT child of PACKAGE ──────────────────────────────
        // Construction order is enforced: children before parent.
        OrderItem childProduct = OrderItem.builder()
                .itemType(ItemType.PRODUCT)
                .sku("SKU-BUILDER-CHILD-001")
                .productReference("PROD-KEYBOARD")
                .quantity(1)
                .price(Price.builder()
                        .value(BigDecimal.valueOf(49.99))
                        .currency(euros)
                        .build())
                .children(List.of())
                .build();

        // ── Top-level item #1: PACKAGE (contains childProduct) ─────────────
        OrderItem packageItemToSave = OrderItem.builder()
                .itemType(ItemType.PACKAGE)
                .sku("PKG-BUILDER-001")
                .productReference("PACKAGE-WORKSTATION")
                .quantity(1)
                .price(Price.builder()
                        .value(BigDecimal.valueOf(249.99))
                        .currency(euros)
                        .build())
                .children(List.of(childProduct))
                .build();

        // ── Top-level item #2: standalone PRODUCT ──────────────────────────
        OrderItem standaloneProduct = OrderItem.builder()
                .itemType(ItemType.PRODUCT)
                .sku("SKU-BUILDER-002")
                .productReference("PROD-MONITOR")
                .quantity(1)
                .price(Price.builder()
                        .value(BigDecimal.valueOf(349.99))
                        .currency(euros)
                        .build())
                .children(List.of())
                .build();

        // ── Order — all links wired manually ────────────────────────────────
        // Forgetting a single .items(), .customer(), or .paymentReference()
        // results in silently persisted inconsistent data.
        Order orderToSave = Order.builder()
                .orderReference("CMD-BUILDER-001")
                .status(OrderStatus.VALIDATED)
                .customer(customer)
                .paymentReference(payment)
                .items(List.of(packageItemToSave, standaloneProduct))
                .build();

        Order savedOrder = orderRepository.save(orderToSave);

        // ── Assertion structure identical to SqlOrderRepositoryTest ─────────
        Order order = orderRepository.findById(savedOrder.getId()).orElseThrow();

        assertThat(order.getStatus()).isEqualTo(OrderStatus.VALIDATED);
        assertThat(order.getCustomer().getCustomerType()).isEqualTo(CustomerType.INDIVIDUAL);
        assertThat(order.getPaymentReference().getStatus()).isEqualTo(PaymentStatus.SUCCESS);
        assertThat(order.getItems()).hasSize(EXPECTED_TOP_LEVEL_ITEMS_SCENARIO_1);

        OrderItem packageItem = order.getItems().stream()
                .filter(i -> i.getItemType() == ItemType.PACKAGE)
                .findFirst()
                .orElseThrow();

        assertThat(packageItem.getChildren()).hasSize(EXPECTED_CHILDREN_IN_PACKAGE);
        assertThat(packageItem.getChildren().getFirst().getItemType()).isEqualTo(ItemType.PRODUCT);
    }

    @Test
    @DisplayName("Builder ⚠️ [Performance] L1 Cache — 3 items built manually, flush/clear then re-reading")
    void should_demonstrate_query_execution_after_flush_and_clear() {

        // ── Infrastructure — reconstructed entirely (no reuse) ──────────────
        Currency euros = Currency.builder()
                .code("EUR").symbol("€").name("Euro")
                .build();

        Address address = Address.builder()
                .street("1 rue de la Paix").postalCode("59000").city("Lille")
                .state("Hauts-de-France").country("France")
                .build();

        Customer customer = Customer.builder()
                .customerType(CustomerType.BUSINESS)
                .firstName("Jean").lastName("Dupont").birthDate(LocalDate.of(1985, 6, 15))
                .email("jean.dupont@example.com").phoneNumber("+33612345678")
                .address(address)
                .build();

        PaymentReference payment = PaymentReference.builder()
                .transactionId("TXN-BUILDER-002")
                .status(PaymentStatus.PENDING)
                .paymentProcessor(PaymentProcessor.STRIPE)
                .build();

        // ── 3 items: each block is an almost identical copy ──────────────────
        // Any modification to the Price or Currency structure ripples here.
        OrderItem item1 = OrderItem.builder()
                .itemType(ItemType.PRODUCT).sku("SKU-BUILDER-A").productReference("PROD-A").quantity(1)
                .price(Price.builder().value(BigDecimal.valueOf(29.99)).currency(euros).build())
                .children(List.of())
                .build();

        OrderItem item2 = OrderItem.builder()
                .itemType(ItemType.PRODUCT).sku("SKU-BUILDER-B").productReference("PROD-B").quantity(2)
                .price(Price.builder().value(BigDecimal.valueOf(59.99)).currency(euros).build())
                .children(List.of())
                .build();

        OrderItem item3 = OrderItem.builder()
                .itemType(ItemType.PRODUCT).sku("SKU-BUILDER-C").productReference("PROD-C").quantity(3)
                .price(Price.builder().value(BigDecimal.valueOf(99.99)).currency(euros).build())
                .children(List.of())
                .build();

        Order orderToSave = Order.builder()
                .orderReference("CMD-BUILDER-002")
                .status(OrderStatus.VALIDATED)
                .customer(customer)
                .paymentReference(payment)
                .items(List.of(item1, item2, item3))
                .build();

        Order savedOrder = orderRepository.save(orderToSave);

        // ── flush() + clear(): L1 cache eviction, guaranteed re-reading ─────
        entityManager.flush();
        entityManager.clear();

        Order reloadedOrder = orderRepository.findById(savedOrder.getId()).orElseThrow();

        assertThat(reloadedOrder.getItems()).hasSize(EXPECTED_TOP_LEVEL_ITEMS_SCENARIO_2);
    }

    @Test
    @DisplayName("Builder ❌ [Reliability] Item forgotten in .items(List.of()) — missing parent-child link")
    void should_handle_bidirectional_mapping_correctly() {

        Currency euros = Currency.builder()
                .code("EUR")
                .symbol("€")
                .name("Euro")
                .build();

        Address address = Address.builder()
                .street("1 rue de la Paix")
                .postalCode("59000")
                .city("Lille")
                .state("Hauts-de-France")
                .country("France")
                .build();

        Customer customer = Customer.builder()
                .customerType(CustomerType.INDIVIDUAL)
                .firstName("Jean")
                .lastName("Dupont")
                .birthDate(LocalDate.of(1985, 6, 15))
                .email("jean.dupont@example.com")
                .phoneNumber("+33612345678")
                .address(address)
                .build();

        PaymentReference payment = PaymentReference.builder()
                .transactionId("TXN-BUILDER-003")
                .status(PaymentStatus.PENDING)
                .paymentProcessor(PaymentProcessor.STRIPE)
                .build();

        // The item is fully built — no compiler error.
        @SuppressWarnings("unused")
        OrderItem item = OrderItem.builder()
                .itemType(ItemType.PRODUCT)
                .sku("SKU-BUILDER-TRAP")
                .productReference("PROD-TRAP")
                .quantity(1)
                .price(Price.builder()
                        .value(BigDecimal.valueOf(29.99))
                        .currency(euros)
                        .build())
                .children(List.of())
                .build();

        // ⚠️ TRAP: .items(List.of()) — the item built above is forgotten.
        // No compiler warning. Save succeeds.
        // After reloading, order.getItems() will be empty.
        Order orderToSave = Order.builder()
                .orderReference("CMD-BUILDER-003")
                .status(OrderStatus.VALIDATED)
                .customer(customer)
                .paymentReference(payment)
                .items(List.of())   // ← item created above deliberately absent
                .build();

        Order savedOrder = orderRepository.save(orderToSave);
        entityManager.flush();
        entityManager.clear();

        Order order = orderRepository.findById(savedOrder.getId()).orElseThrow();

        // Since the link was never established, order.getItems() is empty.
        // Same behavior as the SQL trap (order_id=NULL), different mechanism.
        assertThrows(
                NoSuchElementException.class,
                () -> order.getItems().iterator().next(),
                "The item was built but forgotten in .items(List.of()): " +
                        "order.getItems() is empty even though the item exists in memory."
        );
    }
}